# To create the conda environment, run:
#   conda env create -f environment.yml
name: "{{cookiecutter.package_name}}"
channels:
  - defaults
  - conda-forge
dependencies:
  - "python={{cookiecutter.python_version}}"
  - pip
  - pip:
      - autopep8
      - flake8{%- if cookiecutter.use_pytest == 'y' %}
      - pytest
      - pytest-cov{%- endif %}
      - "-e ."
